### ISSUE TITLE
Register stanza error

### ISSUE THREAD

**Issue by mandado** [strophe/strophejs-plugin-register#1]
Trying use this plugin, i get this error: 

```
<body xmlns='http://jabber.org/protocol/httpbind'><iq xmlns='jabber:client' type='error'><query xmlns='jabber:iq:register'><username>juliet</username><password>R0m30</password></query><error code='400' type='modify'><bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas' xml:lang='en'>Missing attribute &apos;id&apos; in tag &lt;iq/&gt; qualified by namespace &apos;jabber:client&apos;</text></error></iq></body>
```

Is a bug? Or I doing something wrong?
my code:  https://gist.github.com/mandado/85d67a7a2a31668b506ff387e563952b

**Comment by sualko** [comment]
Which XMPP server do you use?

**Comment by mandado** [comment]
I using ejabberd-17.03.beta

**Comment by sualko** [comment]
Can you post the request which triggered this error?

**Comment by mandado** [comment]
print from requests:
![register_post_data](https://cloud.githubusercontent.com/assets/2823627/23959957/5a7c5d68-0985-11e7-81b6-a2197ed456a4.png)
![response_register_post_data](https://cloud.githubusercontent.com/assets/2823627/23959960/5ae661c2-0985-11e7-9a61-2af10aab6890.png)
![register_try](https://cloud.githubusercontent.com/assets/2823627/23959959/5ac62100-0985-11e7-89b9-ca8e6f8a7817.png)
![response_register_try](https://cloud.githubusercontent.com/assets/2823627/23959961/5aec53c0-0985-11e7-8974-8f2f3807ab7c.png)
![request_01](https://cloud.githubusercontent.com/assets/2823627/23959958/5ac38486-0985-11e7-9380-189eedfdd5b9.png)
![response_request_01](https://cloud.githubusercontent.com/assets/2823627/23959963/5b054e48-0985-11e7-8fe9-ac0862d1bb1d.png)

**Comment by sualko** [comment]
I think this is a bug. Can you try to replace `conn.send` with `conn.sendIQ` in the plugin?

**Comment by mandado** [comment]
This worked, but message return is: denied by acl. this is maybe a configuration problem.

**Comment by sualko** [comment]
Great news. Can you create a pull request?

**Comment by mandado** [comment]
Yes. I can do this and send more later.
